name: f1_application
description: Webstar Coding Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  http: ^0.13.5
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  workmanager: ^0.5.1
  url_launcher: ^6.0.20
  country: ^2.0.3
  flag: ^6.0.0
  autocomplete_textfield: ^2.0.1
  age_calculator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/avatar.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/avatar.png"
  windows:
    generate: true
    image_path: "assets/images/avatar.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/avatar.png"

flutter:
  uses-material-design: true

  fonts:
  - family: OleoScript
    fonts:
      - asset: assets/fonts/OleoScript-Regular.ttf
      - asset: assets/fonts/OleoScript-Bold.ttf

  - family: Titillium
    fonts:
      - asset: assets/fonts/TitilliumWeb-Black.ttf
      - asset: assets/fonts/TitilliumWeb-Bold.ttf
      - asset: assets/fonts/TitilliumWeb-BoldItalic.ttf
      - asset: assets/fonts/TitilliumWeb-Italic.ttf
      - asset: assets/fonts/TitilliumWeb-Regular.ttf

  - family: Formula1
    fonts:
      - asset: assets/fonts/Formula1-Black.ttf
      - asset: assets/fonts/Formula1-Bold.ttf
      - asset: assets/fonts/Formula1-Regular.ttf
      - asset: assets/fonts/Formula1-Wide.ttf

  assets:
    - assets/images/Rectangle1.png
    - assets/images/F1-Logo-.jpg
    - assets/images/F1-Logo-1993-.jpg
    - assets/images/F1-Logo-1987-.jpg
    - assets/images/F1-Logo-1985-.jpg
    - assets/images/default.jpg
