import 'package:flag/flag_enum.dart';

class Countries {
  static Map<String, dynamic> getByCode(String code) {
    return countryList.firstWhere((element) =>
    element["code"].toString().toUpperCase() == code.toUpperCase(),
      orElse: () => {});
  }

  static Map<String, dynamic> getByName(String name) {
    return countryList.firstWhere((element) =>
    element["name"].toString().toLowerCase() == name.toLowerCase(),
      orElse: () => {});
  }
  
  static Map<String, dynamic> getByNationality(String nationality) {
    return countryList.firstWhere((element) =>
    element["nationality"].toString().toLowerCase() == nationality.toLowerCase(),
      orElse: () => {});
  }


  static List<Map<String, dynamic>> countryList = [
    {"code": "AD", "name": "Andorra", "flagsCode": FlagsCode.AD , "nationality": ""},
    {"code": "AE", "name": "United Arab Emirates", "flagsCode": FlagsCode.AE , "nationality": "Emirati"},
    {"code": "AF", "name": "Afghanistan", "flagsCode": FlagsCode.AF , "nationality": "Afghan"},
    {"code": "AG", "name": "Antigua and Barbuda", "flagsCode": FlagsCode.AG , "nationality": ""},
    {"code": "AL", "name": "Albania", "flagsCode": FlagsCode.AL , "nationality": "Albanian"},
    {"code": "AM", "name": "Armenia", "flagsCode": FlagsCode.AM , "nationality": ""},
    {"code": "AO", "name": "Angola", "flagsCode": FlagsCode.AO , "nationality": ""},
    {"code": "AR", "name": "Argentina", "flagsCode": FlagsCode.AR , "nationality": "Argentine"},
    {"code": "AT", "name": "Austria", "flagsCode": FlagsCode.AT , "nationality": "Austrian"},
    {"code": "AU", "name": "Australia", "flagsCode": FlagsCode.AU , "nationality": "Australian"},
    {"code": "AZ", "name": "Azerbaijan", "flagsCode": FlagsCode.AZ , "nationality": ""},
    {"code": "BA", "name": "Bosnia and Herzegovina", "flagsCode": FlagsCode.BA , "nationality": ""},
    {"code": "BB", "name": "Barbados", "flagsCode": FlagsCode.BB , "nationality": ""},
    {"code": "BD", "name": "Bangladesh", "flagsCode": FlagsCode.BD , "nationality": "Bangladeshi"},
    {"code": "BE", "name": "Belgium", "flagsCode": FlagsCode.BE , "nationality": "Belgian"},
    {"code": "BF", "name": "Burkina Faso", "flagsCode": FlagsCode.BF , "nationality": ""},
    {"code": "BG", "name": "Bulgaria", "flagsCode": FlagsCode.BG , "nationality": "Bulgarian"},
    {"code": "BH", "name": "Bahrain", "flagsCode": FlagsCode.BH , "nationality": ""},
    {"code": "BI", "name": "Burundi", "flagsCode": FlagsCode.BI , "nationality": ""},
    {"code": "BJ", "name": "Benin", "flagsCode": FlagsCode.BJ , "nationality": ""},
    {"code": "BN", "name": "Brunei Darussalam", "flagsCode": FlagsCode.BN , "nationality": ""},
    {"code": "BO", "name": "Bolivia", "flagsCode": FlagsCode.BO , "nationality": "Bolivian"},
    {"code": "BR", "name": "Brazil", "flagsCode": FlagsCode.BR , "nationality": "Brazilian"},
    {"code": "BS", "name": "Bahamas", "flagsCode": FlagsCode.BS , "nationality": ""},
    {"code": "BT", "name": "Bhutan", "flagsCode": FlagsCode.BT , "nationality": ""},
    {"code": "BW", "name": "Botswana", "flagsCode": FlagsCode.BW , "nationality": "Batswana"},
    {"code": "BY", "name": "Belarus", "flagsCode": FlagsCode.BY , "nationality": ""},
    {"code": "BZ", "name": "Belize", "flagsCode": FlagsCode.BZ , "nationality": ""},
    {"code": "CA", "name": "Canada", "flagsCode": FlagsCode.CA , "nationality": "Canadian"},
    {"code": "CD", "name": "Congo, The Democratic Republic of the", "flagsCode": FlagsCode.CD , "nationality": ""},
    {"code": "CF", "name": "Central African Republic", "flagsCode": FlagsCode.CF , "nationality": ""},
    {"code": "CG", "name": "Congo", "flagsCode": FlagsCode.CG , "nationality": ""},
    {"code": "CH", "name": "Switzerland", "flagsCode": FlagsCode.CH , "nationality": "Swiss"},
    {"code": "CI", "name": "Côte d'Ivoire", "flagsCode": FlagsCode.CI , "nationality": ""},
    {"code": "CL", "name": "Chile", "flagsCode": FlagsCode.CL , "nationality": "Chilean"},
    {"code": "CM", "name": "Cameroon", "flagsCode": FlagsCode.CM , "nationality": "Cameroonian"},
    {"code": "CN", "name": "China", "flagsCode": FlagsCode.CN , "nationality": "Chinese"},
    {"code": "CO", "name": "Colombia", "flagsCode": FlagsCode.CO , "nationality": "Colombian"},
    {"code": "CR", "name": "Costa Rica", "flagsCode": FlagsCode.CR , "nationality": "Costa Rican"},
    {"code": "CU", "name": "Cuba", "flagsCode": FlagsCode.CU , "nationality": "Cuban"},
    {"code": "CV", "name": "Cabo Verde", "flagsCode": FlagsCode.CV , "nationality": ""},
    {"code": "CY", "name": "Cyprus", "flagsCode": FlagsCode.CY , "nationality": ""},
    {"code": "CZ", "name": "Czechia", "flagsCode": FlagsCode.CZ , "nationality": ""},
    {"code": "DE", "name": "Germany", "flagsCode": FlagsCode.DE , "nationality": "German"},
    {"code": "DJ", "name": "Djibouti", "flagsCode": FlagsCode.DJ , "nationality": ""},
    {"code": "DK", "name": "Denmark", "flagsCode": FlagsCode.DK , "nationality": "Danish"},
    {"code": "DM", "name": "Dominica", "flagsCode": FlagsCode.DM , "nationality": "Dominican"},
    {"code": "DO", "name": "Dominican Republic", "flagsCode": FlagsCode.DO , "nationality": "Dominican"},
    {"code": "DZ", "name": "Algeria", "flagsCode": FlagsCode.DZ , "nationality": "Algerian"},
    {"code": "EC", "name": "Ecuador", "flagsCode": FlagsCode.EC , "nationality": "Ecuadorian"},
    {"code": "EE", "name": "Estonia", "flagsCode": FlagsCode.EE , "nationality": "Estonian"},
    {"code": "EG", "name": "Egypt", "flagsCode": FlagsCode.EG , "nationality": "Egyptian"},
    {"code": "EH", "name": "Western Sahara", "flagsCode": FlagsCode.EH , "nationality": ""},
    {"code": "ER", "name": "Eritrea", "flagsCode": FlagsCode.ER , "nationality": ""},
    {"code": "ES", "name": "Spain", "flagsCode": FlagsCode.ES , "nationality": "Spanish"},
    {"code": "ET", "name": "Ethiopia", "flagsCode": FlagsCode.ET , "nationality": "Ethiopian"},
    {"code": "FI", "name": "Finland", "flagsCode": FlagsCode.FI , "nationality": "Finnish"},
    {"code": "FJ", "name": "Fiji", "flagsCode": FlagsCode.FJ , "nationality": "Fijian"},
    {"code": "FM", "name": "Micronesia, Federated States of", "flagsCode": FlagsCode.FM , "nationality": ""},
    {"code": "FR", "name": "France", "flagsCode": FlagsCode.FR , "nationality": "French"},
    {"code": "GA", "name": "Gabon", "flagsCode": FlagsCode.GA , "nationality": ""},
    {"code": "GB", "name": "United Kingdom", "flagsCode": FlagsCode.GB , "nationality": "British"},
    {"code": "GD", "name": "Grenada", "flagsCode": FlagsCode.GD , "nationality": ""},
    {"code": "GE", "name": "Georgia", "flagsCode": FlagsCode.GE , "nationality": ""},
    {"code": "GH", "name": "Ghana", "flagsCode": FlagsCode.GH , "nationality": "Ghanaian"},
    {"code": "GM", "name": "Gambia", "flagsCode": FlagsCode.GM , "nationality": ""},
    {"code": "GN", "name": "Guinea", "flagsCode": FlagsCode.GN , "nationality": ""},
    {"code": "GQ", "name": "Equatorial Guinea", "flagsCode": FlagsCode.GQ , "nationality": ""},
    {"code": "GR", "name": "Greece", "flagsCode": FlagsCode.GR , "nationality": "Greek"},
    {"code": "GT", "name": "Guatemala", "flagsCode": FlagsCode.GT , "nationality": "Guatemalan"},
    {"code": "GW", "name": "Guinea-Bissau", "flagsCode": FlagsCode.GW , "nationality": ""},
    {"code": "GY", "name": "Guyana", "flagsCode": FlagsCode.GY , "nationality": ""},
    {"code": "HK", "name": "Hong Kong", "flagsCode": FlagsCode.HK , "nationality": ""},
    {"code": "HN", "name": "Honduras", "flagsCode": FlagsCode.HN , "nationality": "Honduran"},
    {"code": "HR", "name": "Croatia", "flagsCode": FlagsCode.HR , "nationality": "Croatian"},
    {"code": "HT", "name": "Haiti", "flagsCode": FlagsCode.HT , "nationality": "Haitian"},
    {"code": "HU", "name": "Hungary", "flagsCode": FlagsCode.HU , "nationality": "Hungarian"},
    {"code": "ID", "name": "Indonesia", "flagsCode": FlagsCode.ID , "nationality": "Indonesian"},
    {"code": "IE", "name": "Ireland", "flagsCode": FlagsCode.IE , "nationality": "Irish"},
    {"code": "IL", "name": "Israel", "flagsCode": FlagsCode.IL , "nationality": "Israeli"},
    {"code": "IN", "name": "India", "flagsCode": FlagsCode.IN , "nationality": "Indian"},
    {"code": "IQ", "name": "Iraq", "flagsCode": FlagsCode.IQ , "nationality": "Iraqi"},
    {"code": "IR", "name": "Iran, Islamic Republic of", "flagsCode": FlagsCode.IR , "nationality": "Iranian"},
    {"code": "IS", "name": "Iceland", "flagsCode": FlagsCode.IS , "nationality": "Icelandic"},
    {"code": "IT", "name": "Italy", "flagsCode": FlagsCode.IT , "nationality": "Italian"},
    {"code": "JM", "name": "Jamaica", "flagsCode": FlagsCode.JM , "nationality": "Jamaican"},
    {"code": "JO", "name": "Jordan", "flagsCode": FlagsCode.JO , "nationality": "Jordanian"},
    {"code": "JP", "name": "Japan", "flagsCode": FlagsCode.JP , "nationality": "Japanese"},
    {"code": "KE", "name": "Kenya", "flagsCode": FlagsCode.KE , "nationality": "Kenyan"},
    {"code": "KG", "name": "Kyrgyzstan", "flagsCode": FlagsCode.KG , "nationality": ""},
    {"code": "KH", "name": "Cambodia", "flagsCode": FlagsCode.KH , "nationality": "Cambodian"},
    {"code": "KI", "name": "Kiribati", "flagsCode": FlagsCode.KI , "nationality": ""},
    {"code": "KM", "name": "Comoros", "flagsCode": FlagsCode.KM , "nationality": ""},
    {"code": "KN", "name": "Saint Kitts and Nevis", "flagsCode": FlagsCode.KN , "nationality": ""},
    {"code": "KP", "name": "North Korea", "flagsCode": FlagsCode.KP , "nationality": ""},
    {"code": "KR", "name": "South Korea", "flagsCode": FlagsCode.KR , "nationality": "Korean"},
    {"code": "KW", "name": "Kuwait", "flagsCode": FlagsCode.KW , "nationality": "Kuwaiti"},
    {"code": "KZ", "name": "Kazakhstan", "flagsCode": FlagsCode.KZ , "nationality": ""},
    {"code": "LA", "name": "Lao People's Democratic Republic", "flagsCode": FlagsCode.LA , "nationality": "Lao"},
    {"code": "LB", "name": "Lebanon", "flagsCode": FlagsCode.LB , "nationality": "Lebanese"},
    {"code": "LC", "name": "Saint Lucia", "flagsCode": FlagsCode.LC , "nationality": ""},
    {"code": "LI", "name": "Liechtenstein", "flagsCode": FlagsCode.LI , "nationality": ""},
    {"code": "LK", "name": "Sri Lanka", "flagsCode": FlagsCode.LK , "nationality": "Sri Lankan"},
    {"code": "LR", "name": "Liberia", "flagsCode": FlagsCode.LR , "nationality": ""},
    {"code": "LS", "name": "Lesotho", "flagsCode": FlagsCode.LS , "nationality": ""},
    {"code": "LT", "name": "Lithuania", "flagsCode": FlagsCode.LT , "nationality": "Lithuanian"},
    {"code": "LU", "name": "Luxembourg", "flagsCode": FlagsCode.LU , "nationality": ""},
    {"code": "LV", "name": "Latvia", "flagsCode": FlagsCode.LV , "nationality": "Latvian"},
    {"code": "LY", "name": "Libya", "flagsCode": FlagsCode.LY , "nationality": "Libyan"},
    {"code": "MA", "name": "Morocco", "flagsCode": FlagsCode.MA , "nationality": "Moroccan"},
    {"code": "MC", "name": "Monaco", "flagsCode": FlagsCode.MC , "nationality": "Monegasque"},
    {"code": "MD", "name": "Moldova", "flagsCode": FlagsCode.MD , "nationality": ""},
    {"code": "ME", "name": "Montenegro", "flagsCode": FlagsCode.ME , "nationality": ""},
    {"code": "MG", "name": "Madagascar", "flagsCode": FlagsCode.MG , "nationality": "Malagasy"},
    {"code": "MH", "name": "Marshall Islands", "flagsCode": FlagsCode.MH , "nationality": ""},
    {"code": "MK", "name": "North Macedonia", "flagsCode": FlagsCode.MK , "nationality": ""},
    {"code": "ML", "name": "Mali", "flagsCode": FlagsCode.ML , "nationality": "Malian"},
    {"code": "MM", "name": "Myanmar", "flagsCode": FlagsCode.MM , "nationality": ""},
    {"code": "MN", "name": "Mongolia", "flagsCode": FlagsCode.MN , "nationality": "Mongolian"},
    {"code": "MO", "name": "Macao", "flagsCode": FlagsCode.MO , "nationality": ""},
    {"code": "MR", "name": "Mauritania", "flagsCode": FlagsCode.MR , "nationality": ""},
    {"code": "MT", "name": "Malta", "flagsCode": FlagsCode.MT , "nationality": "Maltese"},
    {"code": "MU", "name": "Mauritius", "flagsCode": FlagsCode.MU , "nationality": ""},
    {"code": "MV", "name": "Maldives", "flagsCode": FlagsCode.MV , "nationality": ""},
    {"code": "MW", "name": "Malawi", "flagsCode": FlagsCode.MW , "nationality": ""},
    {"code": "MX", "name": "Mexico", "flagsCode": FlagsCode.MX , "nationality": "Mexican"},
    {"code": "MY", "name": "Malaysia", "flagsCode": FlagsCode.MY , "nationality": "Malaysian"},
    {"code": "MZ", "name": "Mozambique", "flagsCode": FlagsCode.MZ , "nationality": "Mozambican"},
    {"code": "NA", "name": "Namibia", "flagsCode": FlagsCode.NA , "nationality": "Namibian"},
    {"code": "NE", "name": "Niger", "flagsCode": FlagsCode.NE , "nationality": ""},
    {"code": "NG", "name": "Nigeria", "flagsCode": FlagsCode.NG , "nationality": "Nigerian"},
    {"code": "NI", "name": "Nicaragua", "flagsCode": FlagsCode.NI , "nationality": "Nicaraguan"},
    {"code": "NL", "name": "Netherlands", "flagsCode": FlagsCode.NL , "nationality": "Dutch"},
    {"code": "NO", "name": "Norway", "flagsCode": FlagsCode.NO , "nationality": "Norwegian"},
    {"code": "NP", "name": "Nepal", "flagsCode": FlagsCode.NP , "nationality": "Nepalese"},
    {"code": "NR", "name": "Nauru", "flagsCode": FlagsCode.NR , "nationality": ""},
    {"code": "NZ", "name": "New Zealand", "flagsCode": FlagsCode.NZ , "nationality": "New Zealand"},
    {"code": "OM", "name": "Oman", "flagsCode": FlagsCode.OM , "nationality": ""},
    {"code": "PA", "name": "Panama", "flagsCode": FlagsCode.PA , "nationality": "Panamanian"},
    {"code": "PE", "name": "Peru", "flagsCode": FlagsCode.PE , "nationality": "Peruvian"},
    {"code": "PG", "name": "Papua New Guinea", "flagsCode": FlagsCode.PG , "nationality": ""},
    {"code": "PH", "name": "Philippines", "flagsCode": FlagsCode.PH , "nationality": "Philippine"},
    {"code": "PK", "name": "Pakistan", "flagsCode": FlagsCode.PK , "nationality": "Pakistani"},
    {"code": "PL", "name": "Poland", "flagsCode": FlagsCode.PL , "nationality": "Polish"},
    {"code": "PS", "name": "Palestine, State of", "flagsCode": FlagsCode.PS , "nationality": ""},
    {"code": "PT", "name": "Portugal", "flagsCode": FlagsCode.PT , "nationality": "Portuguese"},
    {"code": "PW", "name": "Palau", "flagsCode": FlagsCode.PW , "nationality": ""},
    {"code": "PY", "name": "Paraguay", "flagsCode": FlagsCode.PY , "nationality": "Paraguayan"},
    {"code": "QA", "name": "Qatar", "flagsCode": FlagsCode.QA , "nationality": ""},
    {"code": "RO", "name": "Romania", "flagsCode": FlagsCode.RO , "nationality": "Romanian"},
    {"code": "RS", "name": "Serbia", "flagsCode": FlagsCode.RS , "nationality": "Serbian"},
    {"code": "RU", "name": "Russian Federation", "flagsCode": FlagsCode.RU , "nationality": "Russian"},
    {"code": "RW", "name": "Rwanda", "flagsCode": FlagsCode.RW , "nationality": ""},
    {"code": "SA", "name": "Saudi Arabia", "flagsCode": FlagsCode.SA , "nationality": "Saudi"},
    {"code": "SB", "name": "Solomon Islands", "flagsCode": FlagsCode.SB , "nationality": ""},
    {"code": "SC", "name": "Seychelles", "flagsCode": FlagsCode.SC , "nationality": ""},
    {"code": "SD", "name": "Sudan", "flagsCode": FlagsCode.SD , "nationality": "Sudanese"},
    {"code": "SE", "name": "Sweden", "flagsCode": FlagsCode.SE , "nationality": "Swedish"},
    {"code": "SG", "name": "Singapore", "flagsCode": FlagsCode.SG , "nationality": "Singaporean"},
    {"code": "SI", "name": "Slovenia", "flagsCode": FlagsCode.SI , "nationality": "Sloven"},
    {"code": "SK", "name": "Slovakia", "flagsCode": FlagsCode.SK , "nationality": "Slovak"},
    {"code": "SL", "name": "Sierra Leone", "flagsCode": FlagsCode.SL , "nationality": ""},
    {"code": "SM", "name": "San Marino", "flagsCode": FlagsCode.SM , "nationality": ""},
    {"code": "SN", "name": "Senegal", "flagsCode": FlagsCode.SN , "nationality": "Senegalese"},
    {"code": "SO", "name": "Somalia", "flagsCode": FlagsCode.SO , "nationality": ""},
    {"code": "SR", "name": "Suriname", "flagsCode": FlagsCode.SR , "nationality": ""},
    {"code": "SS", "name": "South Sudan", "flagsCode": FlagsCode.SS , "nationality": ""},
    {"code": "ST", "name": "Sao Tome and Principe", "flagsCode": FlagsCode.ST , "nationality": ""},
    {"code": "SV", "name": "El Salvador", "flagsCode": FlagsCode.SV , "nationality": "Salvadorian"},
    {"code": "SY", "name": "Syrian Arab Republic", "flagsCode": FlagsCode.SY , "nationality": ""},
    {"code": "SZ", "name": "Eswatini", "flagsCode": FlagsCode.SZ , "nationality": ""},
    {"code": "TD", "name": "Chad", "flagsCode": FlagsCode.TD , "nationality": ""},
    {"code": "TG", "name": "Togo", "flagsCode": FlagsCode.TG , "nationality": ""},
    {"code": "TH", "name": "Thailand", "flagsCode": FlagsCode.TH , "nationality": "Thai"},
    {"code": "TJ", "name": "Tajikistan", "flagsCode": FlagsCode.TJ , "nationality": "Tajikistani"},
    {"code": "TL", "name": "Timor-Leste", "flagsCode": FlagsCode.TL , "nationality": ""},
    {"code": "TM", "name": "Turkmenistan", "flagsCode": FlagsCode.TM , "nationality": ""},
    {"code": "TN", "name": "Tunisia", "flagsCode": FlagsCode.TN , "nationality": "Tunisian"},
    {"code": "TO", "name": "Tonga", "flagsCode": FlagsCode.TO , "nationality": "Tongan"},
    {"code": "TR", "name": "Turkey", "flagsCode": FlagsCode.TR , "nationality": "Turkish"},
    {"code": "TT", "name": "Trinidad and Tobago", "flagsCode": FlagsCode.TT , "nationality": ""},
    {"code": "TV", "name": "Tuvalu", "flagsCode": FlagsCode.TV , "nationality": ""},
    {"code": "TW", "name": "Taiwan", "flagsCode": FlagsCode.TW , "nationality": "Taiwanese"},
    {"code": "TZ", "name": "Tanzania", "flagsCode": FlagsCode.TZ , "nationality": ""},
    {"code": "UA", "name": "Ukraine", "flagsCode": FlagsCode.UA , "nationality": "Ukrainian"},
    {"code": "UG", "name": "Uganda", "flagsCode": FlagsCode.UG , "nationality": ""},
    {"code": "US", "name": "United States", "flagsCode": FlagsCode.US , "nationality": "American"},
    {"code": "UY", "name": "Uruguay", "flagsCode": FlagsCode.UY , "nationality": "Uruguayan"},
    {"code": "UZ", "name": "Uzbekistan", "flagsCode": FlagsCode.UZ , "nationality": ""},
    {"code": "VA", "name": "Holy See (Vatican City State)", "flagsCode": FlagsCode.VA , "nationality": ""},
    {"code": "VC", "name": "Saint Vincent and the Grenadines", "flagsCode": FlagsCode.VC , "nationality": ""},
    {"code": "VE", "name": "Venezuela", "flagsCode": FlagsCode.VE , "nationality": "Venezuelan"},
    {"code": "VN", "name": "Vietnam", "flagsCode": FlagsCode.VN , "nationality": "Vietnamese"},
    {"code": "VU", "name": "Vanuatu", "flagsCode": FlagsCode.VU , "nationality": ""},
    {"code": "WS", "name": "Samoa", "flagsCode": FlagsCode.WS , "nationality": ""},
    {"code": "YE", "name": "Yemen", "flagsCode": FlagsCode.YE , "nationality": ""},
    {"code": "ZA", "name": "South Africa", "flagsCode": FlagsCode.ZA , "nationality": "South African"},
    {"code": "ZM", "name": "Zambia", "flagsCode": FlagsCode.ZM , "nationality": "Zambian"},
    {"code": "ZW", "name": "Zimbabwe", "flagsCode": FlagsCode.ZW , "nationality": "Zimbabwean"}
  ];
}
